check_opkg: Make sure package database is up to date

diff --git a/check_opkg b/check_opkg
--- a/check_opkg
+++ b/check_opkg
@@ -14,6 +14,14 @@ dropbear
 nrpe
 "
 
+# just make sure package database is updated
+opkg --verbosity=0 update
+
+if [[ $? -ne 0 ]]; then
+	echo "CRITICAL - package database could not be updated"
+	exit 2
+fi
+
 UPGRADABLE_PACKAGES=$(opkg list-upgradable)
 UPGRADABLE_CRITICAL=""
 UPGRADABLE_NORMAL=""
